TravelToLearn/Models/Siniflar/TarihiMekanlar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TravelToLearn.Models.Siniflar
{
    public class TarihiMekanlar
    {
        [Key]
        public int ID { get; set; }
        public string TMekanBaslik { get; set; }
        public string TMekanBilgi { get; set; }
        public string TMekanImage { get; set; }
        public int SehirID { get; set; }
        public string SehirAdi { get; set; }
    }
}

TravelToLearn/Controllers/TarihiMekanlarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelToLearn.Models.Siniflar;

namespace TravelToLearn.Controllers
{
    public class TarihiMekanlarController : Controller
    {
        // GET: TarihiMekanlar
        Context c = new Context();

        public ActionResult Index()
        {
            var degerler = c.TarihiMekanlars.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult Ara(string ara)
        {
            return View("Ara", c.TarihiMekanlars .Where(x => x.SehirAdi.Contains(ara) ||
            ara == null).ToList());
        }
    }
}

TravelToLearn/Views/TarihiMekanlar/Ara.cshtml
@using TravelToLearn.Models.Siniflar
@model List<TarihiMekanlar>
@{
    ViewBag.Title = "Ara";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<html>
<head>
    <link href="~/web2/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/web2/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>

</head>
<body>
    <div class="single">
        <div class="container">
            <div class="col-md-8 single-main">
                <div class="single-grid">
                    @foreach (var x in Model)
                    {
                        <p>@x.TMekanBaslik</p>
                        <br />
                        <img src="@x.TMekanImage" style="width:500px;height:300px;" alt="" />
                        <br /> <br />
                        <p>@x.TMekanBilgi</p>
                        <div class="clear"></div>
                    }
                </div>
            </div>
        </div>
    </div>
</body>
</html>

TravelToLearn/Views/TarihiMekanlar/Index.cshtml
@using TravelToLearn.Models.Siniflar
@model List<TarihiMekanlar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}
@using (Html.BeginForm("Ara", "TarihiMekanlar", FormMethod.Get))
{
    <p>
        <br />
        <b>Tarihi Mekan Adı: </b> @Html.TextBox("ara")
        <input type="submit" value="Ara" />
    </p>
}
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <link href="~/web2/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/web2/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>


</head>
<body>
    <!---header---->
    <div class="header">
        <div class="container">
            <div class="clearfix"></div>

        </div>
    </div>
    <!--/header-->
    <div class="single">
        <div class="container">
            <div class="col-md-8 single-main">
                @foreach (var x in Model)
                {
                    <div class="single-grid">
                        <img src="@x.TMekanImage" alt="" style="width:500px;height:300px;" />
                        <br /> <br />
                        <a href="/Restoranlar/Index/@x.ID">@x.TMekanBaslik</a>
                        <p>
                            @x.TMekanBilgi
                        </p>
                    </div>
                    <br /> <br />
                }
            </div>
            @*<div class="col-md-4 side-content">
                <div class="recent">
                    <h3>SON ŞEHİRLER</h3>
                    @foreach (var y in Model)
                    {
                        <ul>
                            <li><a href="/Blog/SehirDetay/@y.ID">@y.Baslik</a></li>
                        </ul>
                    }
                </div>*@
            @*<div class="comments">
                   <h3>SON YORUMLAR</h3>
                   @foreach (var z in Model.Deger2)
                    {
                        <ul>
                            <li><a href="/Blog/SehirDetay/@z.ID">@z.Yorum</a></li>
                        </ul>
                    }
                </div>*@
        </div>
        <div class="clearfix"></div>
    </div>
</body>
</html>